name: Step 2, Reply and Upvote

# This step triggers when a user adds a discussion comment or reaction.
# When both a comment and ðŸ‘ reaction are detected, this workflow updates from step 2 to step 3.

on:
  discussion_comment:
    types: [created]
  reaction:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  check_engagement:
    name: On Comment and Reaction
    needs: get_current_step
    if: >-
      ${{
        !github.event.repository.is_template &&
        needs.get_current_step.outputs.current_step == 2 &&
        (
          github.event_name == 'discussion_comment' ||
          (github.event_name == 'reaction' && github.event.reaction.content == '+1')
        )
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Prepare a branch and pull request
        run: |
          echo "Make sure we are on step 2"
          if [ "$(cat .github/steps/-step.txt)" != 2 ]
          then
            echo "Current step is not 2"
            exit 0
          fi

          echo "Make a branch"
          BRANCH=step-3-mark-answered
          git checkout -b $BRANCH

          echo "Update README to unlock Step 3"
          sed -i.bak 's/<!--STEP 2-->/<!--STEP 3-->/' README/2-reply-and-upvote.md

          echo "Make a commit"
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add README/2-reply-and-upvote.md
          git commit --message="âœ… Step 2 complete: Replied and upvoted!"

          echo "Push"
          git push --set-upstream origin $BRANCH

          echo "Restore main"
          git checkout main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update to step 3
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 2
          to_step: 3
          branch_name: step-3-mark-answered

